# Generated by Django 5.0.3 on 2024-04-04 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_category', models.CharField(max_length=100)),
                ('task_location', models.CharField(max_length=100)),
                ('task_min_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('task_max_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('task_type', models.CharField(choices=[('fixed_price', 'Fixed Price Project'), ('hourly', 'Hourly Project')], max_length=20)),
                ('task_skills', models.CharField(max_length=255)),
                ('task_description', models.TextField()),
                ('task_images', models.ImageField(upload_to='task_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
