# Generated by Django 5.0.3 on 2024-04-04 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
