# Generated by Django 5.0.3 on 2024-04-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_category_taskcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Fixed Price', 'Fixed Price Project'), ('Hourly Rate', 'Hourly Project')], max_length=20),
        ),
    ]
