# Generated by Django 5.0.3 on 2024-04-15 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_task_task_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerBookmarked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bookmarked_freelancer', models.ManyToManyField(related_name='bookmarked_freelancer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TaskCategory',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=models.CharField(choices=[('Solar Installation', 'Solar Installation'), ('Solar Maintenance', 'Solar Maintenance'), ('CCTV Installation', 'CCTV Installation'), ('CCTV Maintenance', 'CCTV Maintenance')], max_length=100),
        ),
    ]
