# Generated by Django 5.0.3 on 2024-04-21 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_task_location_task_task_lga_task_task_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_skills',
        ),
    ]
