# Generated by Django 5.0.3 on 2024-04-21 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_task_task_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_images',
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_files/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.task')),
            ],
        ),
    ]
