# Generated by Django 5.0.3 on 2024-04-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_taskbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbid',
            name='expected_delivery_time_measurement',
            field=models.CharField(default='days', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskbid',
            name='expected_delivery_time',
            field=models.IntegerField(),
        ),
    ]
