# Generated by Django 5.0.3 on 2024-05-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_task_accepted_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbid',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
