# Generated by Django 5.0.3 on 2024-05-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_taskbid_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbid',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
