# Generated by Django 5.0.3 on 2024-05-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_employer_bookmarked_freelancers_and_more'),
        ('dashboard', '0019_alter_taskbid_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_category', models.CharField(choices=[('review', 'review'), ('bid', 'bid'), ('task expiring', 'task expiring')], max_length=50)),
                ('read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employer')),
            ],
        ),
    ]
