# Generated by Django 5.0.3 on 2024-05-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_employernotification_task_employernotification_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerreview',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='freelancerreview',
            name='reviewer',
        ),
        migrations.DeleteModel(
            name='EmployerReview',
        ),
        migrations.DeleteModel(
            name='FreelancerReview',
        ),
    ]
