# Generated by Django 5.0.3 on 2024-05-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_employernote_freelancernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='employernote',
            name='priority',
            field=models.CharField(default='hi', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancernote',
            name='priority',
            field=models.CharField(default='hi', max_length=20),
            preserve_default=False,
        ),
    ]
