# Generated by Django 5.0.3 on 2024-05-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_taskpayment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpayment',
            name='order_id',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
