# Generated by Django 5.0.3 on 2024-05-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_taskpayment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpayment',
            name='release_payment',
            field=models.BooleanField(default=False),
        ),
    ]
