# Generated by Django 5.0.3 on 2024-05-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_taskpayment_release_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
