# Generated by Django 5.0.3 on 2024-05-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_privatemessage_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employernotification',
            name='notification_category',
            field=models.CharField(choices=[('review', 'review'), ('bid', 'bid'), ('task expiring', 'task expiring'), ('message', 'message')], max_length=50),
        ),
        migrations.AlterField(
            model_name='freelancernotification',
            name='notification_category',
            field=models.CharField(choices=[('review', 'review'), ('hired', 'hired'), ('due date', 'due date'), ('message', 'message')], max_length=50),
        ),
    ]
