# Generated by Django 5.0.3 on 2024-06-01 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_remove_task_completed_on_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerreview',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.task'),
        ),
    ]
