# Generated by Django 5.0.3 on 2024-06-01 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_freelancerreview_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerreview',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.task'),
        ),
    ]
