# Generated by Django 5.0.3 on 2024-04-16 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nationality', models.CharField(default='Nigeria', max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('lga', models.CharField(blank=True, max_length=100, null=True)),
                ('tagline', models.CharField(blank=True, max_length=250, null=True)),
                ('self_introduction', models.TextField(blank=True, null=True)),
                ('user_additional_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to='accounts.useradditionalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_additional_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to='accounts.useradditionalinformation')),
                ('bookmarked_freelancers', models.ManyToManyField(blank=True, related_name='bookmarkers', to='accounts.freelancer')),
            ],
        ),
    ]
