# Generated by Django 5.0.3 on 2024-04-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_freelancer_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='speciality',
            field=models.CharField(blank=True, choices=[('Solar Installation', 'Solar Installation'), ('Solar Maintenance', 'Solar Maintenance'), ('CCTV Installation', 'CCTV Installation'), ('CCTV Maintenance', 'CCTV Maintenance')], max_length=100, null=True),
        ),
    ]
