# Generated by Django 5.0.3 on 2024-04-17 07:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_freelancer_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='minimum_pay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useradditionalinformation',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dmpxni4ku/image/upload/v1713334275/user-avatar-placeholder_dfzivc.png', max_length=255, verbose_name='image'),
        ),
    ]
