# Generated by Django 5.0.3 on 2024-04-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_freelancer_minimum_pay_and_more'),
        ('dashboard', '0014_remove_task_task_images_taskfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='bookmarked_freelancers',
        ),
        migrations.AddField(
            model_name='employer',
            name='bookmark_freelancer',
            field=models.ManyToManyField(blank=True, to='accounts.freelancer'),
        ),
        migrations.AddField(
            model_name='employer',
            name='bookmark_task',
            field=models.ManyToManyField(blank=True, to='dashboard.task'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='bookmark_freelancer',
            field=models.ManyToManyField(blank=True, to='accounts.freelancer'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='bookmark_task',
            field=models.ManyToManyField(blank=True, to='dashboard.task'),
        ),
    ]
